version: "3"
services:
    db:
        image: mysql:8.0.12
        restart: always
        volumes:
            - ./docker/data:/var/lib/mysql/
        environment:
            - MYSQL_ROOT_PASSWORD=sampledb
            - MYSQL_DATABASE=test
            - MYSQL_USER=intadd
            - MYSQL_PASSWORD=intadd
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "3306:3306"
    redis:
        image: redis
        command: --port 6379
        ports: 
            - 6379:6379
    django:
        build:
            context: .
            dockerfile: ./web-service/Dockerfile
        environment:
            - DJANGO_DEBUG=True
            - DJANGO_REDIS_HOST=redis
            - DJANGO_REDIS_PORT=6379
            - DJANGO_DB_HOST=db
            - DJANGO_DB_PORT=3306
            - DJANGO_DB_NAME=test
            - DJANGO_DB_USERNAME=intadd
            - DJANGO_DB_PASSWORD=intadd
            - DJANGO_SECRET_KEY=dev_secret_key
        ports:
            - "80:80"
        command: python manage.py migrate 
        command: python manage.py runserver 0.0.0.0:80
        depends_on: 
            - db
        volumes:
            - ./web-service/:/app/
